#!/bin/sh
# athena starting script by rowla
# Correção UNIX & tradução PT-BR: By Spell Master
# 
# **** [ATENÇÃO!!!] *****
# Não editar ou salvar esse arquivo no windows!!!

# ######################################### #
#       ____                     _          #
#      /    |                   | |_        #
#     /     |_ __ ____  __ _  __| |_  __ _  #
#    /  /|  | '__/  __|/ _` |/ _  | |/ _` | #
#   /  __   | | |  |__| (_| | (_| | | (_| | #
#  /  /  |  |_|  \____|\__,_|\__,_|_|\__,_| #
# /__/   |__|                               #
#                                           #
# ######################################### #
# Idealizado por: Spell Master              #
# ######################################### #

PATH=./:$PATH

L_SRV=login-server
C_SRV=char-server
M_SRV=map-server

print_start() {
#    more << EOF
echo "Servidor Iniciando..."
echo " (c) 2003 Athena Project"
echo "  Ver. Spell Master (2018)"
echo ""
echo "Verificando..."
#EOF
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "$i  does not exist, or can't run."
            echo "Stop. Check your compile."
            exit 1;
        fi
    done

#    more << EOF
echo "Verificacao completada."
#EOF
}


case $1 in
    'iniciar')
        print_start
        check_files

        exec ./${L_SRV}&
    echo $! > .${L_SRV}.pid
        exec ./${C_SRV}&
    echo $! > .${C_SRV}.pid
        exec ./${M_SRV}&
    echo $! > .${M_SRV}.pid

        echo "Iniciado"
;;
    'parar')
    for i in .${L_SRV}.pid .${C_SRV}.pid .${M_SRV}.pid
        do
        if [ -e ./$i ]; then
            kill $(cat $i)
            rm $i
        fi
        done
;;
    'reiniciar')
        $0 stop
        $0 start
;;
    *)
        echo "Uso: servidor { iniciar | parar | reiniciar }"
;;
esac
