/*-----------------------------------------------------------------*\
|              ____                     _                           |
|             /    |                   | |_                         |
|            /     |_ __ ____  __ _  __| |_  __ _                   |
|           /  /|  | '__/  __|/ _` |/ _  | |/ _` |                  |
|          /  __   | | |  |__| (_| | (_| | | (_| |                  |
|         /  /  |  |_|  \____|\__,_|\__,_|_|\__,_|                  |
|        /__/   |__|  [ Ragnarok Emulator ]                         |
|                                                                   |
+-------------------------------------------------------------------+
| - Nota: Mapas que terão status Noite e Dia                        |
\*-----------------------------------------------------------------*/

abbey01	mapflag	nightenabled
abbey02	mapflag	nightenabled
abbey03	mapflag	nightenabled
abyss_01	mapflag	nightenabled
abyss_02	mapflag	nightenabled
abyss_03	mapflag	nightenabled
alb2trea	mapflag	nightenabled
alberta	mapflag	nightenabled
alde_dun01	mapflag	nightenabled
alde_dun02	mapflag	nightenabled
alde_dun03	mapflag	nightenabled
alde_dun04	mapflag	nightenabled
alde_gld	mapflag	nightenabled
aldebaran	mapflag	nightenabled
ama_fild01	mapflag	nightenabled
amatsu	mapflag	nightenabled
anthell01	mapflag	nightenabled
anthell02	mapflag	nightenabled
aru_gld	mapflag	nightenabled
ayo_dun01	mapflag	nightenabled
ayo_dun02	mapflag	nightenabled
ayo_fild01	mapflag	nightenabled
ayo_fild02	mapflag	nightenabled
ayothaya	mapflag	nightenabled
bat_a01	mapflag	nightenabled
bat_a02	mapflag	nightenabled
bat_b01	mapflag	nightenabled
bat_b02	mapflag	nightenabled
bat_c01	mapflag	nightenabled
bat_c02	mapflag	nightenabled
bat_c03	mapflag	nightenabled
beach_dun	mapflag	nightenabled
beach_dun2	mapflag	nightenabled
beach_dun3	mapflag	nightenabled
bif_fild01	mapflag	nightenabled
bif_fild02	mapflag	nightenabled
bra_dun01	mapflag	nightenabled
bra_dun02	mapflag	nightenabled
bra_fild01	mapflag	nightenabled
brasilis	mapflag	nightenabled
c_tower1	mapflag	nightenabled
c_tower2	mapflag	nightenabled
c_tower3	mapflag	nightenabled
c_tower4	mapflag	nightenabled
cmd_fild01	mapflag	nightenabled
cmd_fild02	mapflag	nightenabled
cmd_fild03	mapflag	nightenabled
cmd_fild04	mapflag	nightenabled
cmd_fild06	mapflag	nightenabled
cmd_fild07	mapflag	nightenabled
cmd_fild08	mapflag	nightenabled
cmd_fild09	mapflag	nightenabled
comodo	mapflag	nightenabled
dew_dun02	mapflag	nightenabled
dew_fild01	mapflag	nightenabled
dewata	mapflag	nightenabled
dic_dun01	mapflag	nightenabled
dic_dun02	mapflag	nightenabled
dic_dun03	mapflag	nightenabled
dic_fild01	mapflag	nightenabled
dic_fild02	mapflag	nightenabled
dicastes01	mapflag	nightenabled
dicastes02	mapflag	nightenabled
e_tower	mapflag	nightenabled
ecl_fild01	mapflag	nightenabled
ecl_hub01	mapflag	nightenabled
eclage	mapflag	nightenabled
ein_dun01	mapflag	nightenabled
ein_dun02	mapflag	nightenabled
ein_fild01	mapflag	nightenabled
ein_fild03	mapflag	nightenabled
ein_fild04	mapflag	nightenabled
ein_fild05	mapflag	nightenabled
ein_fild06	mapflag	nightenabled
ein_fild07	mapflag	nightenabled
ein_fild08	mapflag	nightenabled
ein_fild09	mapflag	nightenabled
ein_fild10	mapflag	nightenabled
einbech	mapflag	nightenabled
einbroch	mapflag	nightenabled
gef_dun00	mapflag	nightenabled
gef_dun01	mapflag	nightenabled
gef_dun02	mapflag	nightenabled
gef_dun03	mapflag	nightenabled
gef_fild00	mapflag	nightenabled
gef_fild01	mapflag	nightenabled
gef_fild02	mapflag	nightenabled
gef_fild03	mapflag	nightenabled
gef_fild04	mapflag	nightenabled
gef_fild05	mapflag	nightenabled
gef_fild06	mapflag	nightenabled
gef_fild07	mapflag	nightenabled
gef_fild08	mapflag	nightenabled
gef_fild09	mapflag	nightenabled
gef_fild10	mapflag	nightenabled
gef_fild11	mapflag	nightenabled
gef_fild13	mapflag	nightenabled
gefenia01	mapflag	nightenabled
gefenia02	mapflag	nightenabled
gefenia03	mapflag	nightenabled
gefenia04	mapflag	nightenabled
geffen	mapflag	nightenabled
gl_cas01	mapflag	nightenabled
gl_cas02	mapflag	nightenabled
gl_church	mapflag	nightenabled
gl_chyard	mapflag	nightenabled
gl_dun01	mapflag	nightenabled
gl_dun02	mapflag	nightenabled
gl_in01	mapflag	nightenabled
gl_knt01	mapflag	nightenabled
gl_knt02	mapflag	nightenabled
gl_prison	mapflag	nightenabled
gl_prison1	mapflag	nightenabled
gl_sew01	mapflag	nightenabled
gl_sew02	mapflag	nightenabled
gl_sew03	mapflag	nightenabled
gl_sew04	mapflag	nightenabled
gl_step	mapflag	nightenabled
glast_01	mapflag	nightenabled
gon_dun01	mapflag	nightenabled
gon_dun02	mapflag	nightenabled
gon_dun03	mapflag	nightenabled
gon_fild01	mapflag	nightenabled
gonryun	mapflag	nightenabled
hu_fild01	mapflag	nightenabled
hu_fild02	mapflag	nightenabled
hu_fild03	mapflag	nightenabled
hu_fild04	mapflag	nightenabled
hu_fild05	mapflag	nightenabled
hu_fild06	mapflag	nightenabled
hugel	mapflag	nightenabled
ice_dun01	mapflag	nightenabled
ice_dun02	mapflag	nightenabled
ice_dun03	mapflag	nightenabled
ice_dun04	mapflag	nightenabled
in_sphinx1	mapflag	nightenabled
in_sphinx2	mapflag	nightenabled
in_sphinx3	mapflag	nightenabled
in_sphinx4	mapflag	nightenabled
in_sphinx5	mapflag	nightenabled
iz_dun00	mapflag	nightenabled
iz_dun01	mapflag	nightenabled
iz_dun02	mapflag	nightenabled
iz_dun03	mapflag	nightenabled
iz_dun04	mapflag	nightenabled
iz_dun05	mapflag	nightenabled
izlu2dun	mapflag	nightenabled
izlude	mapflag	nightenabled
jawaii	mapflag	nightenabled
juperos_01	mapflag	nightenabled
juperos_02	mapflag	nightenabled
lhz_dun01	mapflag	nightenabled
lhz_dun02	mapflag	nightenabled
lhz_dun03	mapflag	nightenabled
lhz_dun04	mapflag	nightenabled
lhz_fild01	mapflag	nightenabled
lhz_fild02	mapflag	nightenabled
lhz_fild03	mapflag	nightenabled
lighthalzen	mapflag	nightenabled
lou_dun01	mapflag	nightenabled
lou_dun02	mapflag	nightenabled
lou_dun03	mapflag	nightenabled
lou_fild01	mapflag	nightenabled
louyang	mapflag	nightenabled
ma_dun01	mapflag	nightenabled
ma_fild01	mapflag	nightenabled
ma_fild02	mapflag	nightenabled
ma_scene01	mapflag	nightenabled
mag_dun01	mapflag	nightenabled
mag_dun02	mapflag	nightenabled
mal_dun01	mapflag	nightenabled
malangdo	mapflag	nightenabled
malaya	mapflag	nightenabled
man_fild01	mapflag	nightenabled
man_fild02	mapflag	nightenabled
man_fild03	mapflag	nightenabled
manuk	mapflag	nightenabled
mid_camp	mapflag	nightenabled
mjo_dun01	mapflag	nightenabled
mjo_dun02	mapflag	nightenabled
mjo_dun03	mapflag	nightenabled
mjolnir_01	mapflag	nightenabled
mjolnir_02	mapflag	nightenabled
mjolnir_03	mapflag	nightenabled
mjolnir_04	mapflag	nightenabled
mjolnir_05	mapflag	nightenabled
mjolnir_06	mapflag	nightenabled
mjolnir_07	mapflag	nightenabled
mjolnir_08	mapflag	nightenabled
mjolnir_09	mapflag	nightenabled
mjolnir_10	mapflag	nightenabled
mjolnir_11	mapflag	nightenabled
mjolnir_12	mapflag	nightenabled
moc_fild01	mapflag	nightenabled
moc_fild02	mapflag	nightenabled
moc_fild03	mapflag	nightenabled
moc_fild07	mapflag	nightenabled
moc_fild11	mapflag	nightenabled
moc_fild12	mapflag	nightenabled
moc_fild13	mapflag	nightenabled
moc_fild16	mapflag	nightenabled
moc_fild17	mapflag	nightenabled
moc_fild18	mapflag	nightenabled
moc_fild19	mapflag	nightenabled
moc_fild20	mapflag	nightenabled
moc_fild21	mapflag	nightenabled
moc_fild22	mapflag	nightenabled
moc_fild22b	mapflag	nightenabled
moc_pryd01	mapflag	nightenabled
moc_pryd02	mapflag	nightenabled
moc_pryd03	mapflag	nightenabled
moc_pryd04	mapflag	nightenabled
moc_pryd05	mapflag	nightenabled
moc_pryd06	mapflag	nightenabled
moc_ruins	mapflag	nightenabled
morocc	mapflag	nightenabled
moscovia	mapflag	nightenabled
mosk_dun01	mapflag	nightenabled
mosk_dun02	mapflag	nightenabled
mosk_dun03	mapflag	nightenabled
mosk_fild01	mapflag	nightenabled
mosk_fild02	mapflag	nightenabled
mosk_ship	mapflag	nightenabled
nameless_i	mapflag	nightenabled
nameless_in	mapflag	nightenabled
nameless_n	mapflag	nightenabled
nif_fild01	mapflag	nightenabled
nif_fild02	mapflag	nightenabled
niflheim	mapflag	nightenabled
nyd_dun01	mapflag	nightenabled
nyd_dun02	mapflag	nightenabled
odin_tem01	mapflag	nightenabled
odin_tem02	mapflag	nightenabled
odin_tem03	mapflag	nightenabled
orcsdun01	mapflag	nightenabled
orcsdun02	mapflag	nightenabled
pay_arche	mapflag	nightenabled
pay_dun00	mapflag	nightenabled
pay_dun01	mapflag	nightenabled
pay_dun02	mapflag	nightenabled
pay_dun03	mapflag	nightenabled
pay_dun04	mapflag	nightenabled
pay_fild01	mapflag	nightenabled
pay_fild02	mapflag	nightenabled
pay_fild03	mapflag	nightenabled
pay_fild04	mapflag	nightenabled
pay_fild05	mapflag	nightenabled
pay_fild06	mapflag	nightenabled
pay_fild07	mapflag	nightenabled
pay_fild08	mapflag	nightenabled
pay_fild09	mapflag	nightenabled
pay_fild10	mapflag	nightenabled
pay_fild11	mapflag	nightenabled
pay_gld	mapflag	nightenabled
payon	mapflag	nightenabled
prontera	mapflag	nightenabled
prt_fild00	mapflag	nightenabled
prt_fild01	mapflag	nightenabled
prt_fild02	mapflag	nightenabled
prt_fild03	mapflag	nightenabled
prt_fild04	mapflag	nightenabled
prt_fild05	mapflag	nightenabled
prt_fild06	mapflag	nightenabled
prt_fild07	mapflag	nightenabled
prt_fild08	mapflag	nightenabled
prt_fild09	mapflag	nightenabled
prt_fild10	mapflag	nightenabled
prt_fild11	mapflag	nightenabled
prt_gld	mapflag	nightenabled
prt_maze01	mapflag	nightenabled
prt_maze02	mapflag	nightenabled
prt_maze03	mapflag	nightenabled
prt_monk	mapflag	nightenabled
prt_sewb1	mapflag	nightenabled
prt_sewb2	mapflag	nightenabled
prt_sewb3	mapflag	nightenabled
prt_sewb4	mapflag	nightenabled
que_dan01	mapflag	nightenabled
que_dan02	mapflag	nightenabled
que_temsky	mapflag	nightenabled
ra_fild01	mapflag	nightenabled
ra_fild03	mapflag	nightenabled
ra_fild04	mapflag	nightenabled
ra_fild05	mapflag	nightenabled
ra_fild06	mapflag	nightenabled
ra_fild08	mapflag	nightenabled
ra_fild12	mapflag	nightenabled
ra_san01	mapflag	nightenabled
ra_san02	mapflag	nightenabled
ra_san03	mapflag	nightenabled
ra_san04	mapflag	nightenabled
ra_san05	mapflag	nightenabled
ra_temple	mapflag	nightenabled
ra_temsky	mapflag	nightenabled
rachel	mapflag	nightenabled
sch_gld	mapflag	nightenabled
spl_fild01	mapflag	nightenabled
spl_fild02	mapflag	nightenabled
spl_fild03	mapflag	nightenabled
splendide	mapflag	nightenabled
thor_v01	mapflag	nightenabled
thor_v02	mapflag	nightenabled
thor_v03	mapflag	nightenabled
treasure01	mapflag	nightenabled
treasure02	mapflag	nightenabled
tur_dun01	mapflag	nightenabled
tur_dun02	mapflag	nightenabled
tur_dun03	mapflag	nightenabled
tur_dun04	mapflag	nightenabled
tur_dun05	mapflag	nightenabled
um_dun01	mapflag	nightenabled
um_dun02	mapflag	nightenabled
um_fild01	mapflag	nightenabled
um_fild02	mapflag	nightenabled
um_fild02	mapflag	nightenabled
um_fild03	mapflag	nightenabled
um_fild03	mapflag	nightenabled
um_fild04	mapflag	nightenabled
um_fild04	mapflag	nightenabled
umbala	mapflag	nightenabled
ve_fild01	mapflag	nightenabled
ve_fild02	mapflag	nightenabled
ve_fild03	mapflag	nightenabled
ve_fild04	mapflag	nightenabled
ve_fild05	mapflag	nightenabled
ve_fild06	mapflag	nightenabled
ve_fild07	mapflag	nightenabled
veins	mapflag	nightenabled
xmas	mapflag	nightenabled
xmas_dun01	mapflag	nightenabled
xmas_dun02	mapflag	nightenabled
xmas_fild01	mapflag	nightenabled
yuno	mapflag	nightenabled
yuno_fild01	mapflag	nightenabled
yuno_fild01	mapflag	nightenabled
yuno_fild02	mapflag	nightenabled
yuno_fild02	mapflag	nightenabled
yuno_fild03	mapflag	nightenabled
yuno_fild03	mapflag	nightenabled
yuno_fild04	mapflag	nightenabled
yuno_fild04	mapflag	nightenabled
yuno_fild06	mapflag	nightenabled
yuno_fild07	mapflag	nightenabled
yuno_fild08	mapflag	nightenabled
yuno_fild09	mapflag	nightenabled
yuno_fild11	mapflag	nightenabled
yuno_fild12	mapflag	nightenabled
