
ayo_in01	mapflag	nomemo
ayo_in02	mapflag	nomemo
alb_ship	mapflag	nomemo
alberta_in	mapflag	nomemo
aldeba_in	mapflag	nomemo
ama_in01	mapflag	nomemo
ama_in02	mapflag	nomemo
ama_test	mapflag	nomemo
cmd_in01	mapflag	nomemo
cmd_in02	mapflag	nomemo
gef_tower	mapflag	nomemo
geffen_in	mapflag	nomemo
gon_in	mapflag	nomemo
in_orcs01	mapflag	nomemo
izlude_in	mapflag	nomemo
jawaii_in	mapflag	nomemo
lou_in01	mapflag	nomemo
lou_in02	mapflag	nomemo
morocc_in	mapflag	nomemo
mosk_in	mapflag	nomemo
mosk_ship	mapflag	nomemo
mosk_fild01	mapflag	nomemo
mosk_fild02	mapflag	nomemo
mosk_dun01	mapflag	nomemo
mosk_dun02	mapflag	nomemo
mosk_dun03	mapflag	nomemo
nameless_in	mapflag	nomemo
niflheim	mapflag	nomemo
nif_in	mapflag	nomemo
new_1-1	mapflag	nomemo
new_1-2	mapflag	nomemo
new_1-3	mapflag	nomemo
payon_in01	mapflag	nomemo
payon_in02	mapflag	nomemo
payon_in03	mapflag	nomemo
prt_castle	mapflag	nomemo
prt_church	mapflag	nomemo
prt_in	mapflag	nomemo
um_in	mapflag	nomemo
xmas_in	mapflag	nomemo
valkyrie	mapflag	nomemo
yuno_in01	mapflag	nomemo
yuno_in02	mapflag	nomemo
yuno_in03	mapflag	nomemo
yuno_in04	mapflag	nomemo
yuno_in05	mapflag	nomemo
yuno	mapflag	nomemo
ein_in01	mapflag	nomemo
airport	mapflag	nomemo
airplane	mapflag	nomemo
airplane_01	mapflag	nomemo
yuno_pre	mapflag	nomemo
lhz_cube	mapflag	nomemo
lhz_in01	mapflag	nomemo
lhz_in02	mapflag	nomemo
lhz_in03	mapflag	nomemo

ra_in01	mapflag	nomemo
ra_temin	mapflag	nomemo
ra_temsky	mapflag	nomemo
ve_in	mapflag	nomemo
ve_in02	mapflag	nomemo
thor_camp	mapflag	nomemo
moc_para01	mapflag	nomemo

alb2trea	mapflag	nomemo
ayo_fild02	mapflag	nomemo
cmd_fild01	mapflag	nomemo
cmd_fild02	mapflag	nomemo
cmd_fild03	mapflag	nomemo
cmd_fild04	mapflag	nomemo
cmd_fild06	mapflag	nomemo
cmd_fild07	mapflag	nomemo
cmd_fild08	mapflag	nomemo
cmd_fild09	mapflag	nomemo
gef_fild02	mapflag	nomemo
gef_fild03	mapflag	nomemo
gef_fild06	mapflag	nomemo
gef_fild08	mapflag	nomemo
gef_fild10	mapflag	nomemo
gef_fild11	mapflag	nomemo
glast_01	mapflag	nomemo
hu_fild01	mapflag	nomemo
hu_fild05	mapflag	nomemo
izlu2dun	mapflag	nomemo
mjolnir_01	mapflag	nomemo
mjolnir_02	mapflag	nomemo
mjolnir_03	mapflag	nomemo
mjolnir_04	mapflag	nomemo
mjolnir_05	mapflag	nomemo
mjolnir_07	mapflag	nomemo
mjolnir_08	mapflag	nomemo
mjolnir_10	mapflag	nomemo
mjolnir_11	mapflag	nomemo
moc_fild01	mapflag	nomemo
moc_fild02	mapflag	nomemo
moc_fild03	mapflag	nomemo
moc_fild16	mapflag	nomemo
moc_fild17	mapflag	nomemo
moc_fild18	mapflag	nomemo
moc_fild20	mapflag	nomemo
moc_fild21	mapflag	nomemo
moc_fild22	mapflag	nomemo
nif_fild01	mapflag	nomemo
nif_fild02	mapflag	nomemo
pay_fild02	mapflag	nomemo
pay_fild04	mapflag	nomemo
pay_fild05	mapflag	nomemo
pay_fild09	mapflag	nomemo
pay_fild10	mapflag	nomemo
pay_fild11	mapflag	nomemo
prt_fild00	mapflag	nomemo
prt_fild03	mapflag	nomemo
prt_fild04	mapflag	nomemo
prt_fild09	mapflag	nomemo
prt_fild10	mapflag	nomemo
prt_fild11	mapflag	nomemo
prt_monk	mapflag	nomemo
um_fild01	mapflag	nomemo
um_fild02	mapflag	nomemo
um_fild03	mapflag	nomemo
yuno_fild02	mapflag	nomemo
yuno_fild03	mapflag	nomemo
yuno_fild04	mapflag	nomemo
yuno_fild07	mapflag	nomemo
yuno_fild08	mapflag	nomemo
yuno_fild09	mapflag	nomemo
ra_fild01	mapflag	nomemo
ra_fild03	mapflag	nomemo
ra_fild04	mapflag	nomemo
ra_fild05	mapflag	nomemo
ra_fild06	mapflag	nomemo
ve_fild01	mapflag	nomemo
ve_fild02	mapflag	nomemo
ve_fild03	mapflag	nomemo
ve_fild04	mapflag	nomemo
ve_fild06	mapflag	nomemo
job_sword1	mapflag	nomemo
job_thief1	mapflag	nomemo
job_star	mapflag	nomemo
job_knt	mapflag	nomemo
job_prist	mapflag	nomemo
job_wiz	mapflag	nomemo
job_hunte	mapflag	nomemo
in_hunter	mapflag	nomemo
in_moc_16	mapflag	nomemo
alde_alche	mapflag	nomemo
job_cru	mapflag	nomemo
job_duncer	mapflag	nomemo
job_monk	mapflag	nomemo
monk_test	mapflag	nomemo
monk_in	mapflag	nomemo
in_rogue	mapflag	nomemo
job_sage	mapflag	nomemo
job_soul	mapflag	nomemo
que_ng	mapflag	nomemo
que_god01	mapflag	nomemo
que_god02	mapflag	nomemo
que_sign01	mapflag	nomemo

que_rachel	mapflag	nomemo
que_san04	mapflag	nomemo
que_thor	mapflag	nomemo

alde_dun01	mapflag	nomemo
alde_dun02	mapflag	nomemo
alde_dun03	mapflag	nomemo
alde_dun04	mapflag	nomemo
anthell01	mapflag	nomemo
anthell02	mapflag	nomemo
ama_dun01	mapflag	nomemo
ama_dun02	mapflag	nomemo
ama_dun03	mapflag	nomemo
ayo_dun01	mapflag	nomemo
ayo_dun02	mapflag	nomemo
beach_dun	mapflag	nomemo
beach_dun2	mapflag	nomemo
beach_dun3	mapflag	nomemo
c_tower1	mapflag	nomemo
c_tower2	mapflag	nomemo
c_tower3	mapflag	nomemo
c_tower4	mapflag	nomemo
ein_dun01	mapflag	nomemo
ein_dun02	mapflag	nomemo
gef_dun00	mapflag	nomemo
gef_dun01	mapflag	nomemo
gef_dun02	mapflag	nomemo
gef_dun03	mapflag	nomemo
gl_cas01	mapflag	nomemo
gl_cas02	mapflag	nomemo
gl_church	mapflag	nomemo
gl_chyard	mapflag	nomemo
gl_dun01	mapflag	nomemo
gl_dun02	mapflag	nomemo
gl_in01	mapflag	nomemo
gl_knt01	mapflag	nomemo
gl_knt02	mapflag	nomemo
gl_prison	mapflag	nomemo
gl_prison1	mapflag	nomemo
gl_sew01	mapflag	nomemo
gl_sew02	mapflag	nomemo
gl_sew03	mapflag	nomemo
gl_sew04	mapflag	nomemo
gl_step	mapflag	nomemo
gld_dun01	mapflag	nomemo
gld_dun02	mapflag	nomemo
gld_dun03	mapflag	nomemo
gld_dun04	mapflag	nomemo
iz_dun00	mapflag	nomemo
iz_dun01	mapflag	nomemo
iz_dun02	mapflag	nomemo
iz_dun03	mapflag	nomemo
iz_dun04	mapflag	nomemo
in_sphinx1	mapflag	nomemo
in_sphinx2	mapflag	nomemo
in_sphinx3	mapflag	nomemo
in_sphinx4	mapflag	nomemo
in_sphinx5	mapflag	nomemo
lou_dun03	mapflag	nomemo
lou_dun02	mapflag	nomemo
lou_dun01	mapflag	nomemo
mag_dun01	mapflag	nomemo
mag_dun02	mapflag	nomemo
moc_pryd01	mapflag	nomemo
moc_pryd02	mapflag	nomemo
moc_pryd03	mapflag	nomemo
moc_pryd04	mapflag	nomemo
moc_pryd05	mapflag	nomemo
moc_pryd06	mapflag	nomemo
moc_prydb1	mapflag	nomemo
mjo_dun01	mapflag	nomemo
mjo_dun02	mapflag	nomemo
mjo_dun03	mapflag	nomemo
orcsdun01	mapflag	nomemo
orcsdun02	mapflag	nomemo
pay_dun00	mapflag	nomemo
pay_dun01	mapflag	nomemo
pay_dun02	mapflag	nomemo
pay_dun03	mapflag	nomemo
pay_dun04	mapflag	nomemo
prt_maze01	mapflag	nomemo
prt_maze02	mapflag	nomemo
prt_maze03	mapflag	nomemo
prt_sewb1	mapflag	nomemo
prt_sewb2	mapflag	nomemo
prt_sewb3	mapflag	nomemo
prt_sewb4	mapflag	nomemo
gon_dun01	mapflag	nomemo
gon_dun02	mapflag	nomemo
gon_dun03	mapflag	nomemo
treasure01	mapflag	nomemo
treasure02	mapflag	nomemo
tur_dun01	mapflag	nomemo
tur_dun02	mapflag	nomemo
tur_dun03	mapflag	nomemo
tur_dun04	mapflag	nomemo
tur_dun05	mapflag	nomemo
um_dun01	mapflag	nomemo
um_dun02	mapflag	nomemo
xmas_dun01	mapflag	nomemo
xmas_dun02	mapflag	nomemo
yggdrasil01	mapflag	nomemo
gefenia01	mapflag	nomemo
gefenia02	mapflag	nomemo
gefenia03	mapflag	nomemo
gefenia04	mapflag	nomemo
lhz_dun01	mapflag	nomemo
lhz_dun02	mapflag	nomemo
lhz_dun03	mapflag	nomemo
juperos_01	mapflag	nomemo
juperos_02	mapflag	nomemo
jupe_area1	mapflag	nomemo
jupe_area2	mapflag	nomemo
jupe_core	mapflag	nomemo
jupe_ele	mapflag	nomemo
jupe_ele_r	mapflag	nomemo
jupe_gate	mapflag	nomemo
jupe_cave	mapflag	nomemo
thana_boss	mapflag	nomemo
tha_scene01	mapflag	nomemo
tha_t01	mapflag	nomemo
tha_t02	mapflag	nomemo
tha_t03	mapflag	nomemo
tha_t04	mapflag	nomemo
tha_t05	mapflag	nomemo
tha_t06	mapflag	nomemo
tha_t07	mapflag	nomemo
tha_t08	mapflag	nomemo
tha_t09	mapflag	nomemo
tha_t10	mapflag	nomemo
tha_t11	mapflag	nomemo
tha_t12	mapflag	nomemo
thana_step	mapflag	nomemo
abyss_01	mapflag	nomemo
abyss_02	mapflag	nomemo
abyss_03	mapflag	nomemo
odin_tem01	mapflag	nomemo
odin_tem02	mapflag	nomemo
odin_tem03	mapflag	nomemo
kh_kiehl02	mapflag	nomemo
kh_kiehl01	mapflag	nomemo
kh_dun02	mapflag	nomemo
kh_dun01	mapflag	nomemo
kh_mansion	mapflag	nomemo
kh_rossi	mapflag	nomemo
kh_school	mapflag	nomemo
kh_vila	mapflag	nomemo
ice_dun01	mapflag	nomemo
ice_dun02	mapflag	nomemo
ice_dun03	mapflag	nomemo
ice_dun04	mapflag	nomemo
ra_san01	mapflag	nomemo
ra_san02	mapflag	nomemo
ra_san03	mapflag	nomemo
ra_san04	mapflag	nomemo
ra_san05	mapflag	nomemo
thor_v01	mapflag	nomemo
thor_v02	mapflag	nomemo
thor_v03	mapflag	nomemo
nameless_i	mapflag	nomemo
nameless_n	mapflag	nomemo
abbey01	mapflag	nomemo
abbey02	mapflag	nomemo
abbey03	mapflag	nomemo

aldeg_cas01	mapflag	nomemo
aldeg_cas02	mapflag	nomemo
aldeg_cas03	mapflag	nomemo
aldeg_cas04	mapflag	nomemo
aldeg_cas05	mapflag	nomemo
gefg_cas01	mapflag	nomemo
gefg_cas02	mapflag	nomemo
gefg_cas03	mapflag	nomemo
gefg_cas04	mapflag	nomemo
gefg_cas05	mapflag	nomemo
payg_cas01	mapflag	nomemo
payg_cas02	mapflag	nomemo
payg_cas03	mapflag	nomemo
payg_cas04	mapflag	nomemo
payg_cas05	mapflag	nomemo
prtg_cas01	mapflag	nomemo
prtg_cas02	mapflag	nomemo
prtg_cas03	mapflag	nomemo
prtg_cas04	mapflag	nomemo
prtg_cas05	mapflag	nomemo
schg_cas01	mapflag	nomemo
schg_cas02	mapflag	nomemo
schg_cas03	mapflag	nomemo
schg_cas04	mapflag	nomemo
schg_cas05	mapflag	nomemo
arug_cas01	mapflag	nomemo
arug_cas02	mapflag	nomemo
arug_cas03	mapflag	nomemo
arug_cas04	mapflag	nomemo
arug_cas05	mapflag	nomemo

prt_are01	mapflag	nomemo

e_tower	mapflag	nomemo

bat_c01	mapflag	nomemo
bat_c02	mapflag	nomemo
bat_c03	mapflag	nomemo
bat_room	mapflag	nomemo
bat_b01	mapflag	nomemo
bat_b02	mapflag	nomemo
bat_a01	mapflag	nomemo
bat_a02	mapflag	nomemo

mid_campin	mapflag	nomemo
man_fild01	mapflag	nomemo
man_fild03	mapflag	nomemo
spl_fild02	mapflag	nomemo
spl_fild03	mapflag	nomemo
moc_fild22b	mapflag	nomemo
que_dan01	mapflag	nomemo
que_dan02	mapflag	nomemo
schg_dun01	mapflag	nomemo
arug_dun01	mapflag	nomemo
nyd_dun01	mapflag	nomemo
nyd_dun02	mapflag	nomemo
manuk	mapflag	nomemo
man_fild02	mapflag	nomemo
man_in01	mapflag	nomemo
splendide	mapflag	nomemo
spl_fild01	mapflag	nomemo
spl_in01	mapflag	nomemo
job3_arch01	mapflag	nomemo
job3_arch02	mapflag	nomemo
job3_guil01	mapflag	nomemo
job3_guil02	mapflag	nomemo
job3_guil03	mapflag	nomemo
job3_rang01	mapflag	nomemo
job3_rang02	mapflag	nomemo
job3_rune01	mapflag	nomemo
job3_rune02	mapflag	nomemo
job3_war01	mapflag	nomemo
job3_gen01	mapflag	nomemo
job3_sha01	mapflag	nomemo
jupe_core2	mapflag	nomemo
s_atelier	mapflag	nomemo
bra_in01	mapflag	nomemo
bra_dun01	mapflag	nomemo
bra_dun02	mapflag	nomemo
dicastes01	mapflag	nomemo
dicastes02	mapflag	nomemo
dic_in01	mapflag	nomemo
dic_fild01	mapflag	nomemo
dic_fild02	mapflag	nomemo
dic_dun01	mapflag	nomemo
dic_dun02	mapflag	nomemo

bif_fild01	mapflag	nomemo
bif_fild02	mapflag	nomemo
mora	mapflag	nomemo
dew_dun01	mapflag	nomemo
dew_dun02	mapflag	nomemo
dew_in01	mapflag	nomemo
dic_dun03	mapflag	nomemo
mal_in01	mapflag	nomemo
mal_in02	mapflag	nomemo
mal_dun01	mapflag	nomemo
iz_dun05	mapflag	nomemo
lhz_dun04	mapflag	nomemo
que_lhz	mapflag	nomemo
ma_scene01	mapflag	nomemo
ma_in01	mapflag	nomemo
ma_dun01	mapflag	nomemo
ma_zif01	mapflag	nomemo
ma_zif02	mapflag	nomemo
ma_zif03	mapflag	nomemo
ma_zif04	mapflag	nomemo
ma_zif05	mapflag	nomemo
ma_zif06	mapflag	nomemo
ma_zif07	mapflag	nomemo
ma_zif08	mapflag	nomemo
ma_zif09	mapflag	nomemo
eclage	mapflag	nomemo
ecl_fild01	mapflag	nomemo
ecl_in01	mapflag	nomemo
ecl_in02	mapflag	nomemo
ecl_in03	mapflag	nomemo
ecl_in04	mapflag	nomemo
ecl_tdun01	mapflag	nomemo
ecl_tdun02	mapflag	nomemo
ecl_tdun03	mapflag	nomemo
ecl_tdun04	mapflag	nomemo
ecl_hub01	mapflag	nomemo

