/*-----------------------------------------------------------------*\
|              ____                     _                           |
|             /    |                   | |_                         |
|            /     |_ __ ____  __ _  __| |_  __ _                   |
|           /  /|  | '__/  __|/ _` |/ _  | |/ _` |                  |
|          /  __   | | |  |__| (_| | (_| | | (_| |                  |
|         /  /  |  |_|  \____|\__,_|\__,_|_|\__,_|                  |
|        /__/   |__|  [ Ragnarok Emulator ]                         |
|                                                                   |
+-------------------------------------------------------------------+
| - Nota: Mapas onde o comando /memo é bloqueado                    |
\*-----------------------------------------------------------------*/

prt_are01	mapflag	nomemo
prt_monk	mapflag	nomemo
alb_ship	mapflag	nomemo
aldebaran	mapflag	nomemo
aldeba_in	mapflag	nomemo
c_tower1	mapflag	nomemo
c_tower2	mapflag	nomemo
c_tower3	mapflag	nomemo
c_tower4	mapflag	nomemo
alde_dun01	mapflag	nomemo
alde_dun02	mapflag	nomemo
alde_dun03	mapflag	nomemo
alde_dun04	mapflag	nomemo
in_hunter	mapflag	nomemo
moc_prydb1	mapflag	nomemo
sec_pri	mapflag	nomemo
yuno_in03	mapflag	nomemo
yuno_in04	mapflag	nomemo
yuno_in05	mapflag	nomemo
yuno_pre	mapflag	nomemo
monk_in	mapflag	nomemo
in_moc_16	mapflag	nomemo
in_rogue	mapflag	nomemo
monk_test	mapflag	nomemo
aldeg_cas01	mapflag	nomemo
aldeg_cas02	mapflag	nomemo
aldeg_cas03	mapflag	nomemo
aldeg_cas04	mapflag	nomemo
aldeg_cas05	mapflag	nomemo
gefg_cas01	mapflag	nomemo
gefg_cas02	mapflag	nomemo
gefg_cas03	mapflag	nomemo
gefg_cas04	mapflag	nomemo
gefg_cas05	mapflag	nomemo
payg_cas01	mapflag	nomemo
payg_cas02	mapflag	nomemo
payg_cas03	mapflag	nomemo
payg_cas04	mapflag	nomemo
payg_cas05	mapflag	nomemo
prtg_cas01	mapflag	nomemo
prtg_cas02	mapflag	nomemo
prtg_cas03	mapflag	nomemo
prtg_cas04	mapflag	nomemo
prtg_cas05	mapflag	nomemo
ama_test	mapflag	nomemo
yggdrasil01	mapflag	nomemo
valkyrie	mapflag	nomemo
himinn	mapflag	nomemo
jawaii	mapflag	nomemo
jawaii_in	mapflag	nomemo
lhz_dun01	mapflag	nomemo
lhz_dun02	mapflag	nomemo
lhz_dun03	mapflag	nomemo
lhz_cube	mapflag	nomemo
lhz_que01	mapflag	nomemo
airplane	mapflag	nomemo
airplane_01	mapflag	nomemo
airport	mapflag	nomemo
y_airport	mapflag	nomemo
lhz_airport	mapflag	nomemo
abyss_01	mapflag	nomemo
abyss_02	mapflag	nomemo
abyss_03	mapflag	nomemo
thana_boss	mapflag	nomemo
tha_scene01	mapflag	nomemo
tha_t01	mapflag	nomemo
tha_t02	mapflag	nomemo
tha_t03	mapflag	nomemo
tha_t04	mapflag	nomemo
tha_t05	mapflag	nomemo
tha_t06	mapflag	nomemo
tha_t07	mapflag	nomemo
tha_t08	mapflag	nomemo
tha_t09	mapflag	nomemo
tha_t10	mapflag	nomemo
tha_t11	mapflag	nomemo
tha_t12	mapflag	nomemo
thana_step	mapflag	nomemo
alde_alche	mapflag	nomemo
que_ng	mapflag	nomemo
juperos_01	mapflag	nomemo
juperos_02	mapflag	nomemo
jupe_area1	mapflag	nomemo
jupe_area2	mapflag	nomemo
jupe_core	mapflag	nomemo
jupe_ele	mapflag	nomemo
jupe_ele_r	mapflag	nomemo
jupe_gate	mapflag	nomemo
jupe_cave	mapflag	nomemo
gefenia01	mapflag	nomemo
gefenia02	mapflag	nomemo
gefenia03	mapflag	nomemo
gefenia04	mapflag	nomemo
que_god01	mapflag	nomemo
que_god02	mapflag	nomemo
que_sign01	mapflag	nomemo
kh_kiehl02	mapflag	nomemo
kh_kiehl01	mapflag	nomemo
kh_dun02	mapflag	nomemo
kh_dun01	mapflag	nomemo
kh_mansion	mapflag	nomemo
kh_rossi	mapflag	nomemo
kh_school	mapflag	nomemo
kh_vila	mapflag	nomemo
odin_tem01	mapflag	nomemo
odin_tem02	mapflag	nomemo
odin_tem03	mapflag	nomemo
ra_san01	mapflag	nomemo
ra_san02	mapflag	nomemo
ra_san03	mapflag	nomemo
ra_san04	mapflag	nomemo
ra_san05	mapflag	nomemo
ra_temin	mapflag	nomemo
ra_temsky	mapflag	nomemo
ra_temple	mapflag	nomemo
que_rachel	mapflag	nomemo
que_san04	mapflag	nomemo
thor_v01	mapflag	nomemo
thor_v02	mapflag	nomemo
thor_v03	mapflag	nomemo
que_thor	mapflag	nomemo
thor_camp	mapflag	nomemo
z_agit	mapflag	nomemo
que_temsky	mapflag	nomemo
nameless_i	mapflag	nomemo
nameless_n	mapflag	nomemo
nameless_in	mapflag	nomemo
abbey01	mapflag	nomemo
abbey02	mapflag	nomemo
abbey03	mapflag	nomemo
bra_dun01	mapflag	nomemo
bra_dun02	mapflag	nomemo
mosk_ship	mapflag	nomemo
mosk_fild01	mapflag	nomemo
mosk_fild02	mapflag	nomemo
mosk_dun01	mapflag	nomemo
mosk_dun02	mapflag	nomemo
mosk_dun03	mapflag	nomemo
mosk_que	mapflag	nomemo
e_tower	mapflag	nomemo
schg_cas01	mapflag	nomemo
schg_cas02	mapflag	nomemo
schg_cas03	mapflag	nomemo
schg_cas04	mapflag	nomemo
schg_cas05	mapflag	nomemo
arug_cas01	mapflag	nomemo
arug_cas02	mapflag	nomemo
arug_cas03	mapflag	nomemo
arug_cas04	mapflag	nomemo
arug_cas05	mapflag	nomemo
schg_dun01	mapflag	nomemo
arug_dun01	mapflag	nomemo
bat_c01	mapflag	nomemo
bat_c02	mapflag	nomemo
bat_c03	mapflag	nomemo
bat_room	mapflag	nomemo
bat_b01	mapflag	nomemo
bat_b02	mapflag	nomemo
bat_a01	mapflag	nomemo
bat_a02	mapflag	nomemo
mid_campin	mapflag	nomemo
moc_fild22b	mapflag	nomemo
manuk	mapflag	nomemo
man_in01	mapflag	nomemo
man_fild01	mapflag	nomemo
man_fild02	mapflag	nomemo
man_fild03	mapflag	nomemo
splendide	mapflag	nomemo
spl_in01	mapflag	nomemo
spl_in02
spl_fild01	mapflag	nomemo
spl_fild02	mapflag	nomemo
spl_fild03	mapflag	nomemo
nyd_dun01	mapflag	nomemo
nyd_dun02	mapflag	nomemo
que_job01	mapflag	nomemo
moc_para01	mapflag	nomemo
que_dan01	mapflag	nomemo
que_dan02	mapflag	nomemo
dicastes01	mapflag	nomemo
dicastes02	mapflag	nomemo
dic_in01	mapflag	nomemo
dic_fild01	mapflag	nomemo
dic_fild02	mapflag	nomemo
dic_dun01	mapflag	nomemo
dic_dun02	mapflag	nomemo
dic_dun03	mapflag	nomemo
mora	mapflag	nomemo
bif_fild01	mapflag	nomemo
bif_fild02	mapflag	nomemo
dewata	mapflag	nomemo
dew_in01	mapflag	nomemo
dew_fild01	mapflag	nomemo
dew_dun01	mapflag	nomemo
dew_dun02	mapflag	nomemo
iz_dun05	mapflag	nomemo
malangdo	mapflag	nomemo
mal_in01	mapflag	nomemo
mal_in02	mapflag	nomemo
mal_dun01	mapflag	nomemo
lhz_dun04	mapflag	nomemo
que_lhz	mapflag	nomemo
malaya	mapflag	nomemo
ma_in01	mapflag	nomemo
ma_fild01	mapflag	nomemo
ma_fild02	mapflag	nomemo
ma_scene01	mapflag	nomemo
ma_dun01	mapflag	nomemo
ma_zif01	mapflag	nomemo
ma_zif02	mapflag	nomemo
ma_zif03	mapflag	nomemo
ma_zif04	mapflag	nomemo
ma_zif05	mapflag	nomemo
ma_zif06	mapflag	nomemo
ma_zif07	mapflag	nomemo
ma_zif08	mapflag	nomemo
ma_zif09	mapflag	nomemo
eclage	mapflag	nomemo
ecl_in01	mapflag	nomemo
ecl_in02	mapflag	nomemo
ecl_in03	mapflag	nomemo
ecl_in04	mapflag	nomemo
ecl_fild01	mapflag	nomemo
ecl_hub01	mapflag	nomemo
que_avan01	mapflag	nomemo
ecl_tdun01	mapflag	nomemo
ecl_tdun02	mapflag	nomemo
ecl_tdun03	mapflag	nomemo
ecl_tdun04	mapflag	nomemo
