/*-----------------------------------------------------------------*\
|              ____                     _                           |
|             /    |   [ Emulador ]    | |_                         |
|            /     |_ __ ____  __ _  __| |_  __ _                   |
|           /  /|  | '__/  __|/ _` |/ _  | |/ _` |                  |
|          /  __   | | |  |__  (_| | (_| | | (_| |                  |
|         /  /  |  |_|  \____|\__,_|\__,_|_|\__,_|                  |
|        /__/   |__|   Ragnarok - Npc Script                        |
|                                                                   |
+-------------------------------------------------------------------+
| - Copyright: Spell Master                                         |
| - Info: Mapas onde o personagem será enviado ao seu ponto de      |
|         retorno quando deslogar.                                  |
\*-----------------------------------------------------------------*/

abbey01	mapflag	nosave	SavePoint
abbey02	mapflag	nosave	SavePoint
abbey03	mapflag	nosave	SavePoint
abyss_01	mapflag	nosave	SavePoint
abyss_02	mapflag	nosave	SavePoint
abyss_03	mapflag	nosave	SavePoint
airplane	mapflag	nosave	SavePoint
airplane_01	mapflag	nosave	SavePoint
airport	mapflag	nosave	SavePoint
alb_ship	mapflag	nosave	SavePoint
alde_dun01	mapflag	nosave	SavePoint
alde_dun02	mapflag	nosave	SavePoint
alde_dun03	mapflag	nosave	SavePoint
alde_dun04	mapflag	nosave	SavePoint
aldeba_in	mapflag	nosave	SavePoint
aldebaran	mapflag	nosave	SavePoint
aldeg_cas01	mapflag	nosave	SavePoint
aldeg_cas02	mapflag	nosave	SavePoint
aldeg_cas03	mapflag	nosave	SavePoint
aldeg_cas04	mapflag	nosave	SavePoint
aldeg_cas05	mapflag	nosave	SavePoint
ama_test	mapflag	nosave	SavePoint
arug_cas01	mapflag	nosave	SavePoint
arug_cas02	mapflag	nosave	SavePoint
arug_cas03	mapflag	nosave	SavePoint
arug_cas04	mapflag	nosave	SavePoint
arug_cas05	mapflag	nosave	SavePoint
arug_dun01	mapflag	nosave	SavePoint
bat_a01	mapflag	nosave	SavePoint
bat_a02	mapflag	nosave	SavePoint
bat_b01	mapflag	nosave	SavePoint
bat_b02	mapflag	nosave	SavePoint
bat_c01	mapflag	nosave	SavePoint
bat_c02	mapflag	nosave	SavePoint
bat_c03	mapflag	nosave	SavePoint
bat_room	mapflag	nosave	SavePoint
bif_fild01	mapflag	nosave	SavePoint
bif_fild02	mapflag	nosave	SavePoint
bra_dun01	mapflag	nosave	SavePoint
bra_dun02	mapflag	nosave	SavePoint
c_tower1	mapflag	nosave	SavePoint
c_tower2	mapflag	nosave	SavePoint
c_tower3	mapflag	nosave	SavePoint
c_tower4	mapflag	nosave	SavePoint
dew_dun01	mapflag	nosave	SavePoint
dew_dun02	mapflag	nosave	SavePoint
dew_fild01	mapflag	nosave	SavePoint
dew_in01	mapflag	nosave	SavePoint
dewata	mapflag	nosave	SavePoint
dic_dun01	mapflag	nosave	SavePoint
dic_dun02	mapflag	nosave	SavePoint
dic_dun03	mapflag	nosave	SavePoint
dic_fild01	mapflag	nosave	SavePoint
dic_fild02	mapflag	nosave	SavePoint
dic_in01	mapflag	nosave	SavePoint
dicastes01	mapflag	nosave	SavePoint
dicastes02	mapflag	nosave	SavePoint
e_tower	mapflag	nosave	SavePoint
ecl_fild01	mapflag	nosave	SavePoint
ecl_hub01	mapflag	nosave	SavePoint
ecl_in01	mapflag	nosave	SavePoint
ecl_in02	mapflag	nosave	SavePoint
ecl_in03	mapflag	nosave	SavePoint
ecl_in04	mapflag	nosave	SavePoint
ecl_tdun01	mapflag	nosave	SavePoint
ecl_tdun02	mapflag	nosave	SavePoint
ecl_tdun03	mapflag	nosave	SavePoint
ecl_tdun04	mapflag	nosave	SavePoint
eclage	mapflag	nosave	SavePoint
gefenia01	mapflag	nosave	SavePoint
gefenia02	mapflag	nosave	SavePoint
gefenia03	mapflag	nosave	SavePoint
gefenia04	mapflag	nosave	SavePoint
gefg_cas01	mapflag	nosave	SavePoint
gefg_cas02	mapflag	nosave	SavePoint
gefg_cas03	mapflag	nosave	SavePoint
gefg_cas04	mapflag	nosave	SavePoint
gefg_cas05	mapflag	nosave	SavePoint
himinn	mapflag	nosave	SavePoint
in_hunter	mapflag	nosave	SavePoint
in_moc_16	mapflag	nosave	SavePoint
in_rogue	mapflag	nosave	SavePoint
iz_dun05	mapflag	nosave	SavePoint
jawaii	mapflag	nosave	SavePoint
jawaii_in	mapflag	nosave	SavePoint
jupe_area1	mapflag	nosave	SavePoint
jupe_area2	mapflag	nosave	SavePoint
jupe_cave	mapflag	nosave	SavePoint
jupe_core	mapflag	nosave	SavePoint
jupe_ele	mapflag	nosave	SavePoint
jupe_ele_r	mapflag	nosave	SavePoint
jupe_gate	mapflag	nosave	SavePoint
juperos_01	mapflag	nosave	SavePoint
juperos_02	mapflag	nosave	SavePoint
kh_dun01	mapflag	nosave	SavePoint
kh_dun02	mapflag	nosave	SavePoint
kh_kiehl01	mapflag	nosave	SavePoint
kh_kiehl02	mapflag	nosave	SavePoint
kh_mansion	mapflag	nosave	SavePoint
kh_rossi	mapflag	nosave	SavePoint
kh_school	mapflag	nosave	SavePoint
kh_vila	mapflag	nosave	SavePoint
lhz_airport	mapflag	nosave	SavePoint
lhz_cube	mapflag	nosave	SavePoint
lhz_dun01	mapflag	nosave	SavePoint
lhz_dun02	mapflag	nosave	SavePoint
lhz_dun03	mapflag	nosave	SavePoint
lhz_dun04	mapflag	nosave	SavePoint
lhz_que01	mapflag	nosave	SavePoint
ma_dun01	mapflag	nosave	SavePoint
ma_fild01	mapflag	nosave	SavePoint
ma_fild02	mapflag	nosave	SavePoint
ma_in01	mapflag	nosave	SavePoint
ma_scene01	mapflag	nosave	SavePoint
ma_zif01	mapflag	nosave	SavePoint
ma_zif02	mapflag	nosave	SavePoint
ma_zif03	mapflag	nosave	SavePoint
ma_zif04	mapflag	nosave	SavePoint
ma_zif05	mapflag	nosave	SavePoint
ma_zif06	mapflag	nosave	SavePoint
ma_zif07	mapflag	nosave	SavePoint
ma_zif08	mapflag	nosave	SavePoint
ma_zif09	mapflag	nosave	SavePoint
mal_dun01	mapflag	nosave	SavePoint
mal_in01	mapflag	nosave	SavePoint
mal_in02	mapflag	nosave	SavePoint
malangdo	mapflag	nosave	SavePoint
malaya	mapflag	nosave	SavePoint
man_fild01	mapflag	nosave	SavePoint
man_fild02	mapflag	nosave	SavePoint
man_fild03	mapflag	nosave	SavePoint
man_in01	mapflag	nosave	SavePoint
manuk	mapflag	nosave	SavePoint
mid_campin	mapflag	nosave	SavePoint
moc_fild22b	mapflag	nosave	SavePoint
moc_para01	mapflag	nosave	SavePoint
moc_prydb1	mapflag	nosave	SavePoint
monk_in	mapflag	nosave	SavePoint
monk_test	mapflag	nosave	SavePoint
mora	mapflag	nosave	SavePoint
mosk_dun01	mapflag	nosave	SavePoint
mosk_dun02	mapflag	nosave	SavePoint
mosk_dun03	mapflag	nosave	SavePoint
mosk_fild01	mapflag	nosave	SavePoint
mosk_fild02	mapflag	nosave	SavePoint
mosk_que	mapflag	nosave	SavePoint
mosk_ship	mapflag	nosave	SavePoint
nameless_i	mapflag	nosave	SavePoint
nameless_in	mapflag	nosave	SavePoint
nameless_n	mapflag	nosave	SavePoint
nyd_dun01	mapflag	nosave	SavePoint
nyd_dun02	mapflag	nosave	SavePoint
odin_tem01	mapflag	nosave	SavePoint
odin_tem02	mapflag	nosave	SavePoint
odin_tem03	mapflag	nosave	SavePoint
payg_cas01	mapflag	nosave	SavePoint
payg_cas02	mapflag	nosave	SavePoint
payg_cas03	mapflag	nosave	SavePoint
payg_cas04	mapflag	nosave	SavePoint
payg_cas05	mapflag	nosave	SavePoint
prt_are01	mapflag	nosave	SavePoint
prt_monk	mapflag	nosave	SavePoint
prtg_cas01	mapflag	nosave	SavePoint
prtg_cas02	mapflag	nosave	SavePoint
prtg_cas03	mapflag	nosave	SavePoint
prtg_cas04	mapflag	nosave	SavePoint
prtg_cas05	mapflag	nosave	SavePoint
que_avan01	mapflag	nosave	SavePoint
que_dan01	mapflag	nosave	SavePoint
que_dan02	mapflag	nosave	SavePoint
que_god01	mapflag	nosave	SavePoint
que_god02	mapflag	nosave	SavePoint
que_job01	mapflag	nosave	SavePoint
que_lhz	mapflag	nosave	SavePoint
que_ng	mapflag	nosave	SavePoint
que_rachel	mapflag	nosave	SavePoint
que_san04	mapflag	nosave	SavePoint
que_sign01	mapflag	nosave	SavePoint
que_temsky	mapflag	nosave	SavePoint
que_thor	mapflag	nosave	SavePoint
ra_san01	mapflag	nosave	SavePoint
ra_san02	mapflag	nosave	SavePoint
ra_san03	mapflag	nosave	SavePoint
ra_san04	mapflag	nosave	SavePoint
ra_san05	mapflag	nosave	SavePoint
ra_temin	mapflag	nosave	SavePoint
ra_temple	mapflag	nosave	SavePoint
ra_temsky	mapflag	nosave	SavePoint
schg_cas01	mapflag	nosave	SavePoint
schg_cas02	mapflag	nosave	SavePoint
schg_cas03	mapflag	nosave	SavePoint
schg_cas04	mapflag	nosave	SavePoint
schg_cas05	mapflag	nosave	SavePoint
schg_dun01	mapflag	nosave	SavePoint
sec_pri	mapflag	nosave	SavePoint
spl_fild01	mapflag	nosave	SavePoint
spl_fild02	mapflag	nosave	SavePoint
spl_fild03	mapflag	nosave	SavePoint
spl_in01	mapflag	nosave	SavePoint
spl_in02	mapflag	nosave	SavePoint
splendide	mapflag	nosave	SavePoint
tha_scene01	mapflag	nosave	SavePoint
tha_t01	mapflag	nosave	SavePoint
tha_t02	mapflag	nosave	SavePoint
tha_t03	mapflag	nosave	SavePoint
tha_t04	mapflag	nosave	SavePoint
tha_t05	mapflag	nosave	SavePoint
tha_t06	mapflag	nosave	SavePoint
tha_t07	mapflag	nosave	SavePoint
tha_t08	mapflag	nosave	SavePoint
tha_t09	mapflag	nosave	SavePoint
tha_t10	mapflag	nosave	SavePoint
tha_t11	mapflag	nosave	SavePoint
tha_t12	mapflag	nosave	SavePoint
thana_boss	mapflag	nosave	SavePoint
thana_step	mapflag	nosave	SavePoint
thor_camp	mapflag	nosave	SavePoint
thor_v01	mapflag	nosave	SavePoint
thor_v02	mapflag	nosave	SavePoint
thor_v03	mapflag	nosave	SavePoint
valkyrie	mapflag	nosave	SavePoint
y_airport	mapflag	nosave	SavePoint
yggdrasil01	mapflag	nosave	SavePoint
yuno_in03	mapflag	nosave	SavePoint
yuno_in04	mapflag	nosave	SavePoint
yuno_in05	mapflag	nosave	SavePoint
yuno_pre	mapflag	nosave	SavePoint
z_agit	mapflag	nosave	SavePoint
