/*-----------------------------------------------------------------*\
|              ____                     _                           |
|             /    |                   | |_                         |
|            /     |_ __ ____  __ _  __| |_  __ _                   |
|           /  /|  | '__/  __|/ _` |/ _  | |/ _` |                  |
|          /  __   | | |  |__| (_| | (_| | | (_| |                  |
|         /  /  |  |_|  \____|\__,_|\__,_|_|\__,_|                  |
|        /__/   |__|  [ Ragnarok Emulator ]                         |
|                                                                   |
+-------------------------------------------------------------------+
|                  Idealizado por: Spell Master                     |
+-------------------------------------------------------------------+
| - Este código é livre para editar, redistribuir de acordo com os  |
| termos da GNU General Public License, publicada sobre conselho    |
| pela Free Software Foundation.                                    |
|                                                                   |
| - Qualquer ato de comercialização desse software está previsto    |
| em leis internacionais, junto com este(s) código(s) você recebeu  |
| uma cópia de licença de uso.                                      |
| - Caso não tenha recebido veja: http://www.gnu.org/licenses/      |
\*-----------------------------------------------------------------*/

#ifndef MAP_PACKETS_ZERO_KEYS_H
#define MAP_PACKETS_ZERO_KEYS_H

#ifndef packetKeys
	#define packetKeys(a,b,c)
#endif

/* This file is autogenerated, please do not commit manual changes */

// 2017-10-19aRagexe_zero, 2017-10-23aRagexe_zero, 2017-10-23bRagexe_zero, 2017-10-23cRagexe_zero, 2017-10-24aRagexe_2_zero, 2017-10-24aRagexe_zero, 2017-10-25bRagexe_zero, 2017-10-27aRagexe_zero, 2017-10-27bRagexe_zero, 2017-10-30aRagexe_zero, 2017-10-31aRagexe_zero, 2017-11-09aRagexe_zero, 2017-11-13aRagexe_zero, 2017-11-13bRagexe_zero
#if PACKETVER == 20171019 || \
    PACKETVER == 20171023 || \
    PACKETVER == 20171024 || \
    PACKETVER == 20171025 || \
    PACKETVER == 20171027 || \
    PACKETVER == 20171030 || \
    PACKETVER == 20171031 || \
    PACKETVER == 20171109 || \
    PACKETVER == 20171113
	packetKeys(0x00000000,0x00000000,0x00000000);
#endif

// 2017-11-15aRagexe_zero, 2017-11-15bRagexe_zero, 2017-11-16aRagexe_zero, 2017-11-17aRagexe_zero
#if PACKETVER == 20171115 || \
    PACKETVER == 20171116 || \
    PACKETVER == 20171117
	packetKeys(0x3B93061D,0x3CB50DCD,0x410A197E);
#endif

// 2017-11-21aRagexe_zero, 2017-11-22aRagexe_zero
#if PACKETVER == 20171121 || \
    PACKETVER == 20171122
	packetKeys(0x195B4DA8,0x6E3A473B,0x126F4B61);
#endif

// 2017-11-23dRagexe_zero
#if PACKETVER == 20171123
	packetKeys(0x6087733A,0x5C5C4AEE,0x0F10408F);
#endif

// 2017-11-27aRagexe_zero, 2017-11-27cRagexe_zero, 2017-11-28aRagexe_zero
#if PACKETVER == 20171127 || \
    PACKETVER == 20171128
	packetKeys(0x141C135C,0x675C275C,0x275C275C);
#endif

// 2017-11-30bRagexe_zero
#if PACKETVER == 20171130
	packetKeys(0x31A04B32,0x3AC96B76,0x1742085D);
#endif

// 2017-12-04bRagexe_zero
#if PACKETVER == 20171204
	packetKeys(0x06A109F1,0x6A953256,0x0A6040A3);
#endif

// 2017-12-06aRagexe_zero, 2017-12-06bRagexe_zero, 2017-12-06cRagexe_zero, 2017-12-06dRagexe_zero, 2017-12-08aRagexe_zero, 2017-12-08cRagexe_zero, 2017-12-08dRagexe_zero, 2017-12-09bRagexe_zero, 2017-12-09cRagexe_zero, 2017-12-10aRagexe_zero, 2017-12-11bRagexe_zero, 2017-12-12aRagexe_zero, 2017-12-13aRagexe_zero, 2017-12-13bRagexe_zero, 2017-12-13cRagexe_zero
#if PACKETVER == 20171206 || \
    PACKETVER == 20171208 || \
    PACKETVER == 20171209 || \
    PACKETVER == 20171210 || \
    PACKETVER == 20171211 || \
    PACKETVER == 20171212 || \
    PACKETVER == 20171213
	packetKeys(0x718D0388,0x56A11525,0x20042F67);
#endif

// 2017-12-14cRagexe_zero
#if PACKETVER == 20171214
	packetKeys(0x6CE1021D,0x77703B04,0x4E722232);
#endif

// 2017-12-20aRagexe_zero, 2017-12-21aRagexe_zero, 2017-12-21bRagexe_zero
#if PACKETVER == 20171220 || \
    PACKETVER == 20171221
	packetKeys(0x1E2047D2,0x7EE31AC2,0x31434F61);
#endif

// 2017-12-27bRagexe_zero, 2017-12-29aRagexe_zero
#if PACKETVER == 20171227 || \
    PACKETVER == 20171229
	packetKeys(0x7CBF0846,0x02F92654,0x22AA5E2D);
#endif

// 2018-01-03aRagexe_zero
#if PACKETVER == 20180103
	packetKeys(0x2A3D4E64,0x7008690C,0x69FF066F);
#endif

// 2018-01-17aRagexe_zero
#if PACKETVER == 20180117
	packetKeys(0x230959EB,0x1CCB0182,0x1FFA2B30);
#endif


#endif /* MAP_PACKETS_ZERO_KEYS_H */
