CREATE USER 'arcadiasqluser'@'localhost' IDENTIFIED BY 'arcadiasqluserpass';
GRANT GRANT OPTION ON *.* TO 'arcadiasqluser'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'arcadiasqluser'@'localhost';
CREATE DATABASE arcadia;
CREATE DATABASE arcadia_logs
