/*
* ARQUIVO SERÁ REMOVIDO E TODOS SEUS VALORES FIXADOS NO CÓDIGO!
* NÃO ALTERAR NADA AQUI PARA EVITAR BUGS NO EMULADOR!!!!
 */

#ifndef CONFIG_RENEWAL_H
#define CONFIG_RENEWAL_H
#define RENEWAL
#endif
